course_links = {
    "poslovna komunikacija i suradnja": "https://www.veleri.hr/hr/kolegij/poslovna-komunikacija-i-suradnja",
    "poslovni procesi u organizacijama": "https://www.veleri.hr/hr/kolegij/poslovni-procesi-u-organizacijama",
    "engleski jezik za informatičare": "https://www.veleri.hr/hr/kolegij/engleski-jezik-za-informaticare",
    "uvod u informacijske i komunikacijske tehnologije": "https://www.veleri.hr/hr/kolegij/uvod-u-informacijske-i-komunikacijske-tehnologije",
    "tjelesna i zdravstvena kultura 1": "https://www.veleri.hr/hr/kolegij/tjelesna-i-zdravstvena-kultura-1-0",
    "proceduralno i modularno programiranje": "https://www.veleri.hr/hr/kolegij/proceduralno-i-modularno-programiranje",
    "matematika za informatičare": "https://www.veleri.hr/hr/kolegij/matematika-za-informaticare",
    "objektno orijentirano programiranje": "https://www.veleri.hr/hr/kolegij/objektno-orijentirano-programiranje",
    "specifikacija korisničkih zahtjeva i modeliranje procesa": "https://www.veleri.hr/hr/kolegij/specifikacija-korisnickih-zahtjeva-i-modeliranje-procesa",
    "računalna grafika": "https://www.veleri.hr/hr/kolegij/racunalna-grafika",
    "modeliranje podataka": "https://www.veleri.hr/hr/kolegij/modeliranje-podataka",
    "operacijski sustavi": "https://www.veleri.hr/hr/kolegij/operacijski-sustavi-0",
    "razvoj poslovne ideje": "https://www.veleri.hr/hr/kolegij/razvoj-poslovne-ideje",
    "tjelesna i zdravstvena kultura 2": "https://www.veleri.hr/hr/kolegij/tjelesna-i-zdravstvena-kultura-2-0",
    "uvod u baze podataka": "https://www.veleri.hr/hr/kolegij/uvod-u-baze-podataka",
    "uvod u računalne mreže": "https://www.veleri.hr/hr/kolegij/uvod-u-racunalne-mreze",
    "razvoj aplikacijskog programskog sučelja": "https://www.veleri.hr/hr/kolegij/razvoj-aplikacijskog-programskog-sucelja",
    "multimedijski sustavi": "https://www.veleri.hr/hr/kolegij/multimedijski-sustavi-0",
    "engleski jezik za projektante": "https://www.veleri.hr/hr/kolegij/engleski-jezik-za-projektante",
    "napredne teme iz operacijskih sustava": "https://www.veleri.hr/hr/kolegij/napredne-teme-iz-operacijskih-sustava",
    "osnove proceduralnog programiranja": "https://www.veleri.hr/hr/kolegij/osnove-proceduralnog-programiranja",
    "uvod u iot sustave": "https://www.veleri.hr/hr/kolegij/uvod-u-iot-sustave",
    "poduzetništvo za informatičare": "https://www.veleri.hr/hr/kolegij/poduzetnistvo-za-informaticare",
    "sustavi baza podataka": "https://www.veleri.hr/hr/kolegij/sustavi-baza-podataka-0",
    "razvoj desktop aplikacija": "https://www.veleri.hr/hr/kolegij/razvoj-desktop-aplikacija",
    "sigurnost informacijskih i komunikacijskih sustava": "https://www.veleri.hr/hr/kolegij/sigurnost-informacijskih-i-komunikacijskih-sustava",
    "sustavi za upravljanje sadržajem i dokumentima": "https://www.veleri.hr/hr/kolegij/sustavi-za-upravljanje-sadrzajem-i-dokumentima",
    "projektni praktikum": "https://www.veleri.hr/hr/kolegij/projektni-praktikum",
    "sistemska infrastruktura za razvoj softvera": "https://www.veleri.hr/hr/kolegij/sistemska-infrastruktura-za-razvoj-softvera",
    "razvoj mobilnih aplikacija": "https://www.veleri.hr/hr/kolegij/razvoj-mobilnih-aplikacija",
    "upravljanje informatičkim projektima": "https://www.veleri.hr/hr/kolegij/upravljanje-informatickim-projektima",
    "razvoj interaktivnih web aplikacija": "https://www.veleri.hr/hr/kolegij/razvoj-interaktivnih-web-aplikacija",
    "osnove umjetne inteligencije": "https://www.veleri.hr/hr/kolegij/osnove-umjetne-inteligencije",
    "poslovna analitika i izvješćivanje": "https://www.veleri.hr/hr/kolegij/poslovna-analitika-i-izvjescivanje",
    "3d modeliranje": "https://www.veleri.hr/hr/kolegij/3d-modeliranje",
    "napredne teme iz sigurnosti informacijskih i komunikacijskih sustava": "https://www.veleri.hr/hr/kolegij/napredne-teme-iz-sigurnosti-informacijskih-i-komunikacijskih-sustava",
    "programsko inženjerstvo (prijediplomski)": "https://www.veleri.hr/hr/kolegij/programsko-inzenjerstvo-1",
    "Digitalni marketing": "https://www.veleri.hr/hr/kolegij/digitalni-marketing",
    "semestralna stručna praksa": "https://www.veleri.hr/hr/kolegij/semestralna-strucna-praksa-6",
    "završni rad": "https://www.veleri.hr/hr/kolegij/zavrsni-rad-8",
    "modeliranje i simulacije": "https://www.veleri.hr/hr/kolegij/modeliranje-i-simulacije",
    "upravljanje bazama podataka": "https://www.veleri.hr/hr/kolegij/upravljanje-bazama-podataka",
    "alati razvoja informacijskih sustava": "https://www.veleri.hr/hr/kolegij/alati-razvoja-informacijskih-sustava",
    "komunikacijske tehnologije": "https://www.veleri.hr/hr/kolegij/komunikacijske-tehnologije",
    "upravljanje kvalitetom informacijskih sustava": "https://www.veleri.hr/hr/kolegij/upravljanje-kvalitetom-informacijskih-sustava",
    "sustavi za vođenje proizvodnih procesa": "https://www.veleri.hr/hr/kolegij/sustavi-za-vodenje-proizvodnih-procesa",
    "kontrola i revizija informacijskih sustava": "https://www.veleri.hr/hr/kolegij/kontrola-i-revizija-informacijskih-sustava",
    "programsko inženjerstvo (diplomski)": "https://www.veleri.hr/hr/kolegij/programsko-inzenjerstvo",
    "izgradnja objektno orijentiranih aplikacija": "https://www.veleri.hr/hr/kolegij/izgradnja-objektno-orijentiranih-aplikacija",
    "izgradnja multimedijskih sustava": "https://www.veleri.hr/hr/kolegij/izgradnja-multimedijskih-sustava",
    "računalno upravljanje složenim sustavima": "https://www.veleri.hr/hr/kolegij/racunalno-upravljanje-slozenim-sustavima",
    "sučelje poslovnih i procesnih sustava": "https://www.veleri.hr/hr/kolegij/sucelje-poslovnih-i-procesnih-sustava",
    "distribuirani sustavi": "https://www.veleri.hr/hr/kolegij/distribuirani-sustavi",
    "modularno programsko inženjerstvo": "https://www.veleri.hr/hr/kolegij/modularno-programsko-inzenjerstvo",
    "sigurnost web aplikacija": "https://www.veleri.hr/hr/kolegij/sigurnost-web-aplikacija",
    "metodika stručnog i istraživačkog rada": "https://www.veleri.hr/hr/kolegij/metodika-strucnog-i-istrazivackog-rada-izborni-predmeti",
    "automatizacija uredskog poslovanja": "https://www.veleri.hr/hr/kolegij/automatizacija-uredskog-poslovanja-izborni-predmet-0",
    "informacijski sustav za potporu odlučivanju": "https://www.veleri.hr/hr/kolegij/informacijski-sustav-za-potporu-odlucivanju-izborni-predmet-0",
    "ux/ui dizajn": "https://www.veleri.hr/hr/kolegij/uxui-dizajn",
    "planiranje informacijskih sustava": "https://www.veleri.hr/hr/kolegij/planiranje-informacijskih-sustava",
    "ergonomija i uporaba računala": "https://www.veleri.hr/hr/kolegij/ergonomija-i-uporaba-racunala",
    "internet tehnologije i e-poslovanje": "https://www.veleri.hr/hr/kolegij/internet-tehnologije-i-e-poslovanje",
    "specijalistička praksa": "https://www.veleri.hr/hr/kolegij/specijalisticka-praksa-0",
    "diplomski rad": "https://www.veleri.hr/hr/kolegij/diplomski-rad"
}