prof_kontakt = {
    "dr. sc. socio. Ozren Rafajac": "https://www.veleri.hr/hr/profil/ozren-rafajac",
    "dr. sc. socio. Davor Širola": "https://www.veleri.hr/hr/profil/davor-sirola",
    "dr. sc. socio. Sabrina Šuman": "https://www.veleri.hr/hr/profil/sabrina-suman",
    "Ivan Šimac": "https://www.veleri.hr/hr/profil/ivan-simac",
    "dr. sc. socio. Elena Krelja Kurelović": "https://www.veleri.hr/hr/profil/elena-krelja-kurelovic",
    "dr. sc. human. Tatjana Šepić": "https://www.veleri.hr/hr/profil/tatjana-sepic",
    "dr. sc. socio. Ida Panev": "https://www.veleri.hr/hr/profil/ida-panev",
    "Bruno Polonijo": "https://www.veleri.hr/hr/profil/bruno-polonijo",
    "Suzana Škarica Stupičić": "https://www.veleri.hr/hr/profil/suzana-skarica-stupicic",
    "mr. sc. Katarina Volarić Nižić": "https://www.veleri.hr/hr/profil/katarina-volaric-nizic",
    "mr. sc. Jasminka Tomljanović": "https://www.veleri.hr/hr/profil/jasminka-tomljanovic",
    "Matea Pešut": "https://www.veleri.hr/hr/profil/matea-pesut",
    "dr. sc. socio. Marina Rauker Koch": "https://www.veleri.hr/hr/profil/marina-rauker-koch",
    "dr. sc. socio. Bernard Vukelić": "https://www.veleri.hr/hr/profil/bernard-vukelic",
    "dr. sc. socio. Alen Jakupović": "https://www.veleri.hr/hr/profil/alen-jakupovic",
    "Vlatka Davidović": "https://www.veleri.hr/hr/profil/vlatka-davidovic",
    "dr. sc. socio. Sanja Raspor Janković": "https://www.veleri.hr/hr/profil/sanja-raspor-jankovic",
    "dr. sc. tech. Andrea Andrijašević": "https://www.veleri.hr/hr/profil/andrea-andrijasevic",
    "dr. sc. socio. Marin Kaluža": "https://www.veleri.hr/hr/profil/marin-kaluza",
    "Martin Golob": "https://www.veleri.hr/hr/profil/martin-golob",
    "MSc Žaklina Šupica": "https://www.veleri.hr/hr/profil/zaklina-supica",
    "dr. sc. human. Sanja Grakalić Plenković": "https://www.veleri.hr/hr/profil/sanja-grakalic-plenkovic",
    "mr. sc. Vesna Krajči": "https://www.veleri.hr/hr/profil/vesna-krajci",
    "Kristina Dundović": "https://www.veleri.hr/hr/profil/kristina-dundovic"
}
